#!/usr/bin/env python3
"""
Upload fraud detection models to Hugging Face Hub
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from huggingface_hub import HfApi, login

def upload_models():
    """Upload fraud_model.pkl and scaler.pkl to Hugging Face Hub"""
    
    # Load environment variables
    load_dotenv()
    
    # Get credentials from environment
    hf_token = os.getenv('HUGGINGFACE_TOKEN')
    hf_repo = os.getenv('HUGGINGFACE_REPO')
    
    if not hf_token:
        raise ValueError("HUGGINGFACE_TOKEN not found in .env file")
    if not hf_repo:
        raise ValueError("HUGGINGFACE_REPO not found in .env file")
    
    print(f"🔐 Logging into Hugging Face Hub...")
    
    # Login to Hugging Face
    login(token=hf_token)
    
    # Initialize API
    api = HfApi()
    
    # Check if model files exist
    model_files = ['fraud_model.pkl', 'scaler.pkl']
    missing_files = []
    
    for file in model_files:
        if not Path(file).exists():
            missing_files.append(file)
    
    if missing_files:
        print(f"❌ Missing model files: {', '.join(missing_files)}")
        print("Please ensure fraud_model.pkl and scaler.pkl are in the root directory")
        return False
    
    print(f"📦 Uploading models to {hf_repo}...")
    
    try:
        # Upload each model file
        for file in model_files:
            print(f"  📤 Uploading {file}...")
            api.upload_file(
                path_or_fileobj=file,
                path_in_repo=file,
                repo_id=hf_repo,
                repo_type="model"
            )
            print(f"  ✅ {file} uploaded successfully")
        
        # Create a README.md for the model repository
        readme_content = """# Fraud Detection Models

This repository contains the trained models for the FraudGuard AI fraud detection system.

## Files

- `fraud_model.pkl`: XGBoost fraud detection model
- `scaler.pkl`: Feature scaler for preprocessing

## Usage

```python
from load_model import load_models

# Load models
fraud_model, scaler = load_models()

# Use for prediction
# scaled_features = scaler.transform(features)
# prediction = fraud_model.predict_proba(scaled_features)
```

## Model Details

- **Algorithm**: XGBoost Classifier
- **Features**: Transaction amount, merchant category, time of day, location mismatch, fraud history, device risk score
- **Output**: Fraud probability (0-1)

Generated by FraudGuard AI system.
"""
        
        print("  📝 Creating README.md...")
        api.upload_file(
            path_or_fileobj=readme_content.encode(),
            path_in_repo="README.md",
            repo_id=hf_repo,
            repo_type="model"
        )
        
        print(f"\n🎉 Success! Models uploaded to Hugging Face Hub")
        print(f"🔗 Repository URL: https://huggingface.co/{hf_repo}")
        
        return True
        
    except Exception as e:
        print(f"❌ Upload failed: {str(e)}")
        return False

if __name__ == "__main__":
    print("🚀 FraudGuard AI - Model Upload Utility")
    print("=" * 50)
    
    success = upload_models()
    
    if success:
        print("\n✨ Upload completed successfully!")
    else:
        print("\n💥 Upload failed. Please check the error messages above.")