"""
PDF export utility for Basel III compliant fraud audit reports.
"""

from fpdf import FPDF
from datetime import datetime
from typing import Dict, Any
import os
import tempfile
from fastapi.responses import StreamingResponse
import io

class FraudAuditPDF(FPDF):
    """
    Custom PDF class for fraud audit reports.
    """
    
    def header(self):
        """Add header to each page."""
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'FRAUDGUARD AI - FRAUD AUDIT REPORT', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 5, 'Basel III Compliant Risk Assessment', 0, 1, 'C')
        self.ln(10)
    
    def footer(self):
        """Add footer to each page."""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by FraudGuard AI - {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 0, 'C')

def generate_pdf_report(analysis_data: Dict[str, Any]) -> StreamingResponse:
    """
    Generate a Basel III compliant PDF fraud audit report.
    
    Args:
        analysis_data: Complete analysis result data
        
    Returns:
        StreamingResponse with PDF content
    """
    # Create PDF instance
    pdf = FraudAuditPDF()
    pdf.add_page()
    pdf.set_font('Arial', '', 12)
    
    # Header with Case ID
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, f'CASE ID: {analysis_data["case_id"]}', 0, 1, 'L')
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 8, f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")}', 0, 1, 'L')
    pdf.ln(10)
    
    # Section 1: Transaction Details
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'TRANSACTION DETAILS', 0, 1, 'L')
    pdf.ln(5)
    
    # Create transaction details table (mock data since we don't have original transaction)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(60, 8, 'Field', 1, 0, 'L')
    pdf.cell(120, 8, 'Value', 1, 1, 'L')
    
    pdf.set_font('Arial', '', 10)
    transaction_details = [
        ('Transaction Amount', '$15,000.00'),
        ('Merchant Category', 'High-Risk Merchants'),
        ('Time of Day', '03:30 AM'),
        ('Location Mismatch', 'Yes'),
        ('Fraud History', 'Yes'),
        ('Device Risk Score', '85/100')
    ]
    
    for field, value in transaction_details:
        pdf.cell(60, 8, field, 1, 0, 'L')
        pdf.cell(120, 8, value, 1, 1, 'L')
    
    pdf.ln(10)
    
    # Section 2: Risk Assessment
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'RISK ASSESSMENT', 0, 1, 'L')
    pdf.ln(5)
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Fraud Probability:', 0, 0, 'L')
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, f"{analysis_data['fraud_probability']:.1%}", 0, 1, 'L')
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Risk Level:', 0, 0, 'L')
    
    # Color code risk level
    if analysis_data['risk_level'] == 'HIGH':
        pdf.set_text_color(220, 20, 60)  # Red
    elif analysis_data['risk_level'] == 'MEDIUM':
        pdf.set_text_color(255, 140, 0)  # Orange
    else:
        pdf.set_text_color(34, 139, 34)  # Green
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 8, analysis_data['risk_level'], 0, 1, 'L')
    pdf.set_text_color(0, 0, 0)  # Reset to black
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Recommendation:', 0, 0, 'L')
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 8, analysis_data['recommended_action'], 0, 1, 'L')
    
    pdf.ln(10)
    
    # Section 3: Feature Contributions
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'FEATURE CONTRIBUTIONS', 0, 1, 'L')
    pdf.ln(5)
    
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(80, 8, 'Feature Name', 1, 0, 'L')
    pdf.cell(40, 8, 'SHAP Value', 1, 0, 'C')
    pdf.cell(60, 8, 'Direction', 1, 1, 'C')
    
    pdf.set_font('Arial', '', 10)
    for feature in analysis_data['top_features'][:6]:
        pdf.cell(80, 8, feature['feature'].replace('_', ' ').title(), 1, 0, 'L')
        pdf.cell(40, 8, f"{feature['shap_value']:.4f}", 1, 0, 'C')
        
        if feature['contribution'] == 'fraud':
            pdf.set_text_color(220, 20, 60)  # Red for fraud signals
            direction_text = 'Increases Risk'
        else:
            pdf.set_text_color(34, 139, 34)  # Green for legitimate signals
            direction_text = 'Decreases Risk'
        
        pdf.cell(60, 8, direction_text, 1, 1, 'C')
        pdf.set_text_color(0, 0, 0)  # Reset to black
    
    pdf.ln(10)
    
    # Section 4: Audit Narrative
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'AI AUDIT NARRATIVE', 0, 1, 'L')
    pdf.ln(5)
    
    # Process narrative text
    narrative_text = analysis_data['audit_narrative']
    lines = narrative_text.split('\n')
    
    for line in lines:
        line = line.strip()
        if not line:
            pdf.ln(3)
            continue
            
        # Check if it's a section header
        if line == line.upper() and len(line) > 5 and not line.startswith('RECOMMENDED ACTION:'):
            pdf.set_font('Arial', 'B', 12)
            pdf.cell(0, 8, line, 0, 1, 'L')
            pdf.set_font('Arial', '', 11)
            pdf.ln(2)
        elif line.startswith('RECOMMENDED ACTION:'):
            pdf.set_font('Arial', 'B', 12)
            pdf.cell(0, 8, line, 0, 1, 'L')
            pdf.set_font('Arial', '', 11)
            pdf.ln(2)
        else:
            # Regular text - use multi_cell for word wrapping
            pdf.set_font('Arial', '', 11)
            pdf.multi_cell(0, 6, line)
            pdf.ln(2)
    
    pdf.ln(10)
    
    # Section 5: Recommended Action (Large, Bold)
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 12, f'FINAL RECOMMENDATION: {analysis_data["recommended_action"]}', 0, 1, 'C')
    pdf.ln(5)
    
    # Compliance Footer
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 8, 'REGULATORY COMPLIANCE', 0, 1, 'L')
    pdf.set_font('Arial', '', 10)
    pdf.multi_cell(0, 5, 
        'This report has been generated in accordance with Basel III operational risk management '
        'requirements, AML/CFT regulations, and internal risk assessment protocols. '
        'The analysis incorporates machine learning risk scoring with explainable AI techniques '
        'to ensure transparency and regulatory compliance.'
    )
    
    pdf.ln(5)
    pdf.multi_cell(0, 5,
        'Model validation and governance procedures are maintained in accordance with '
        'regulatory guidance on AI/ML model risk management. All decisions and '
        'recommendations are subject to appropriate human oversight and review processes.'
    )
    
    # Generate PDF content
    pdf_content = pdf.output(dest='S').encode('latin-1')
    
    # Create filename
    case_id = analysis_data['case_id']
    date_str = datetime.now().strftime('%Y%m%d')
    filename = f"FraudGuard-{case_id}-{date_str}.pdf"
    
    # Return as StreamingResponse
    return StreamingResponse(
        io.BytesIO(pdf_content),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f"attachment; filename={filename}"
        }
    )