"""
PDF export utility for Basel III compliant fraud audit reports.
"""

from fpdf import FPDF
from datetime import datetime
from typing import Dict, Any
import os
import tempfile

class FraudAuditPDF(FPDF):
    """
    Custom PDF class for fraud audit reports.
    """
    
    def header(self):
        """Add header to each page."""
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'FRAUDGUARD AI - FRAUD AUDIT REPORT', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 5, 'Basel III Compliant Risk Assessment', 0, 1, 'C')
        self.ln(10)
    
    def footer(self):
        """Add footer to each page."""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by FraudGuard AI - {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 0, 'C')

def generate_pdf_report(analysis_data: Dict[str, Any]) -> str:
    """
    Generate a Basel III compliant PDF fraud audit report.
    
    Args:
        analysis_data: Complete analysis result data
        
    Returns:
        Path to the generated PDF file
    """
    # Create PDF instance
    pdf = FraudAuditPDF()
    pdf.add_page()
    pdf.set_font('Arial', '', 12)
    
    # Report Header Information
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'EXECUTIVE SUMMARY', 0, 1, 'L')
    pdf.ln(5)
    
    # Case Information
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Case ID:', 0, 0, 'L')
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, analysis_data['case_id'], 0, 1, 'L')
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Timestamp:', 0, 0, 'L')
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, analysis_data['timestamp'], 0, 1, 'L')
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Risk Level:', 0, 0, 'L')
    pdf.set_font('Arial', 'B', 12)
    
    # Color code risk level
    if analysis_data['risk_level'] == 'HIGH':
        pdf.set_text_color(220, 20, 60)  # Red
    elif analysis_data['risk_level'] == 'MEDIUM':
        pdf.set_text_color(255, 140, 0)  # Orange
    else:
        pdf.set_text_color(34, 139, 34)  # Green
    
    pdf.cell(0, 8, analysis_data['risk_level'], 0, 1, 'L')
    pdf.set_text_color(0, 0, 0)  # Reset to black
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Fraud Score:', 0, 0, 'L')
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, f"{analysis_data['fraud_probability']:.1%}", 0, 1, 'L')
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Recommendation:', 0, 0, 'L')
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 8, analysis_data['recommended_action'], 0, 1, 'L')
    
    pdf.ln(10)
    
    # Risk Drivers Section
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'RISK DRIVERS ANALYSIS', 0, 1, 'L')
    pdf.ln(5)
    
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 6, 'Top risk contributing factors identified by the ML model:', 0, 1, 'L')
    pdf.ln(3)
    
    for i, feature in enumerate(analysis_data['top_features'][:6], 1):
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(10, 6, f'{i}.', 0, 0, 'L')
        pdf.cell(80, 6, feature['feature'].replace('_', ' ').title(), 0, 0, 'L')
        
        pdf.set_font('Arial', '', 11)
        contribution_text = f"({feature['contribution']} signal)"
        if feature['contribution'] == 'fraud':
            pdf.set_text_color(220, 20, 60)  # Red for fraud signals
        else:
            pdf.set_text_color(34, 139, 34)  # Green for legitimate signals
        
        pdf.cell(60, 6, contribution_text, 0, 0, 'L')
        pdf.set_text_color(0, 0, 0)  # Reset to black
        
        pdf.cell(0, 6, f'Impact: {feature["shap_value"]:.4f}', 0, 1, 'L')
    
    pdf.ln(10)
    
    # Audit Narrative Section
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'REGULATORY AUDIT NARRATIVE', 0, 1, 'L')
    pdf.ln(5)
    
    # Split narrative into paragraphs and format
    narrative_text = analysis_data['audit_narrative']
    
    # Remove markdown formatting for PDF
    narrative_text = narrative_text.replace('**', '')
    
    pdf.set_font('Arial', '', 11)
    
    # Split by sections (assuming sections are separated by double newlines)
    sections = narrative_text.split('\n\n')
    
    for section in sections:
        if section.strip():
            # Check if it's a header (starts with capital letters)
            lines = section.strip().split('\n')
            for line in lines:
                if line.strip():
                    # Simple heuristic: if line is short and has no lowercase, it's likely a header
                    if len(line) < 50 and line.isupper():
                        pdf.set_font('Arial', 'B', 12)
                        pdf.cell(0, 8, line, 0, 1, 'L')
                        pdf.set_font('Arial', '', 11)
                    else:
                        # Regular text - use multi_cell for word wrapping
                        pdf.multi_cell(0, 6, line)
            pdf.ln(3)
    
    pdf.ln(10)
    
    # Compliance Footer
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 8, 'REGULATORY COMPLIANCE', 0, 1, 'L')
    pdf.set_font('Arial', '', 10)
    pdf.multi_cell(0, 5, 
        'This report has been generated in accordance with Basel III operational risk management '
        'requirements, AML/CFT regulations, and internal risk assessment protocols. '
        'The analysis incorporates machine learning risk scoring with explainable AI techniques '
        'to ensure transparency and regulatory compliance.'
    )
    
    pdf.ln(5)
    pdf.multi_cell(0, 5,
        'Model validation and governance procedures are maintained in accordance with '
        'regulatory guidance on AI/ML model risk management. All decisions and '
        'recommendations are subject to appropriate human oversight and review processes.'
    )
    
    # Generate temporary file
    temp_dir = tempfile.gettempdir()
    filename = f"fraud_audit_{analysis_data['case_id']}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(temp_dir, filename)
    
    # Save PDF
    pdf.output(filepath)
    
    return filepath