"""
PDF export utility for Basel III compliant fraud audit reports.
"""

from fpdf import FPDF
from datetime import datetime
from typing import Dict, Any
from fastapi.responses import Response

class FraudAuditPDF(FPDF):
    """
    Custom PDF class for fraud audit reports.
    """
    
    def header(self):
        """Add header to each page."""
        self.set_font('Arial', 'B', 20)
        self.cell(0, 15, 'FRAUDGUARD AI', 0, 1, 'C')
        self.set_font('Arial', '', 12)
        self.cell(0, 8, 'Basel III Compliant Fraud Detection Report', 0, 1, 'C')
        self.ln(5)
        # Horizontal line
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(10)
    
    def footer(self):
        """Add footer to each page."""
        self.set_y(-20)
        self.set_font('Arial', 'I', 9)
        self.cell(0, 10, 'Generated by FraudGuard AI | Basel III Compliant | AML/CFT Standards', 0, 0, 'C')

def generate_pdf_report(analysis_data: Dict[str, Any]) -> Response:
    """
    Generate a Basel III compliant PDF fraud audit report.
    
    Args:
        analysis_data: Complete analysis result data
        
    Returns:
        Response with PDF content
    """
    # Create PDF instance
    pdf = FraudAuditPDF()
    pdf.add_page()
    
    # Case ID and Timestamp
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, f'Case ID: {str(analysis_data.get("case_id", "N/A"))}', 0, 1, 'L')
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 8, f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")}', 0, 1, 'L')
    pdf.ln(10)
    
    # Section 1: Transaction Details
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'SECTION 1 — TRANSACTION DETAILS', 0, 1, 'L')
    pdf.ln(5)
    
    # Transaction details table
    pdf.set_font('Arial', 'B', 10)
    col_width = 30
    pdf.cell(col_width, 8, 'Amount', 1, 0, 'C')
    pdf.cell(col_width, 8, 'Category', 1, 0, 'C')
    pdf.cell(col_width, 8, 'Time', 1, 0, 'C')
    pdf.cell(col_width, 8, 'Location', 1, 0, 'C')
    pdf.cell(col_width, 8, 'Fraud History', 1, 0, 'C')
    pdf.cell(col_width, 8, 'Device Score', 1, 1, 'C')
    
    pdf.set_font('Arial', '', 10)
    pdf.cell(col_width, 8, '$15,000', 1, 0, 'C')
    pdf.cell(col_width, 8, 'High-Risk', 1, 0, 'C')
    pdf.cell(col_width, 8, '03:30 AM', 1, 0, 'C')
    pdf.cell(col_width, 8, 'Mismatch', 1, 0, 'C')
    pdf.cell(col_width, 8, 'Yes', 1, 0, 'C')
    pdf.cell(col_width, 8, '85/100', 1, 1, 'C')
    pdf.ln(10)
    
    # Section 2: Risk Assessment
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'SECTION 2 — RISK ASSESSMENT', 0, 1, 'L')
    pdf.ln(5)
    
    fraud_prob = analysis_data.get('fraud_probability', 0)
    risk_level = str(analysis_data.get('risk_level', 'UNKNOWN'))
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 8, f'Fraud Probability: {fraud_prob:.1%}', 0, 1, 'L')
    pdf.cell(0, 8, f'Risk Level: {risk_level}', 0, 1, 'L')
    pdf.ln(10)
    
    # Section 3: Feature Contributions
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'SECTION 3 — FEATURE CONTRIBUTIONS', 0, 1, 'L')
    pdf.ln(5)
    
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(80, 8, 'Feature', 1, 0, 'L')
    pdf.cell(40, 8, 'SHAP Value', 1, 0, 'C')
    pdf.cell(60, 8, 'Direction', 1, 1, 'C')
    
    pdf.set_font('Arial', '', 10)
    top_features = analysis_data.get('top_features', [])
    for feature in top_features[:6]:
        feature_name = str(feature.get('feature', 'Unknown')).replace('_', ' ').title()
        shap_val = feature.get('shap_value', 0)
        contribution = str(feature.get('contribution', 'unknown'))
        
        pdf.cell(80, 8, feature_name, 1, 0, 'L')
        pdf.cell(40, 8, f'{shap_val:.4f}', 1, 0, 'C')
        direction = 'Increases Risk' if contribution == 'fraud' else 'Decreases Risk'
        pdf.cell(60, 8, direction, 1, 1, 'C')
    
    pdf.ln(10)
    
    # Section 4: Audit Narrative
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'SECTION 4 — AUDIT NARRATIVE', 0, 1, 'L')
    pdf.ln(5)
    
    # Clean narrative text (remove markdown)
    narrative = str(analysis_data.get('audit_narrative', 'No narrative available'))
    clean_narrative = narrative.replace('**', '')
    
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 6, clean_narrative)
    pdf.ln(10)
    
    # Section 5: Recommended Action
    pdf.set_font('Arial', 'B', 16)
    recommended_action = str(analysis_data.get('recommended_action', 'UNKNOWN'))
    pdf.cell(0, 12, f'RECOMMENDED ACTION: {recommended_action}', 0, 1, 'C')
    
    # Generate PDF bytes
    pdf_bytes = pdf.output()
    
    # Create filename
    case_id = str(analysis_data.get('case_id', 'UNKNOWN'))
    filename = f"FraudGuard-{case_id}.pdf"
    
    # Return as Response
    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f"attachment; filename={filename}"
        }
    )